"""Create spells table

Revision ID: 40663106dbcf
Revises: 
Create Date: 2025-11-29 21:20:27.685776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40663106dbcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Create the spells table with all required columns and indexes.
    
    This migration creates the initial database schema for storing spell data,
    including indexes on id, title, and error_type for efficient querying.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_pattern', sa.Text(), nullable=False),
    sa.Column('solution_code', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spells_error_type'), 'spells', ['error_type'], unique=False)
    op.create_index(op.f('ix_spells_id'), 'spells', ['id'], unique=False)
    op.create_index(op.f('ix_spells_title'), 'spells', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Drop the spells table and all associated indexes.
    
    This migration reverses the upgrade by removing the spells table
    and all its indexes from the database.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spells_title'), table_name='spells')
    op.drop_index(op.f('ix_spells_id'), table_name='spells')
    op.drop_index(op.f('ix_spells_error_type'), table_name='spells')
    op.drop_table('spells')
    # ### end Alembic commands ###
